name = "purple-leopard"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "purple-leopard_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "purple-leopard.wasm"
command = "npm run build:release"
